code --install-extension 4ops.terraform
code --install-extension akamud.vscode-theme-onedark
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension atommaterial.a-file-icon-vscode
code --install-extension davidanson.vscode-markdownlint
code --install-extension dustypomerleau.rust-syntax
code --install-extension eamodio.gitlens
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension korekontrol.saltstack
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension rafaelrenanpacheco.darcula-theme
code --install-extension redhat.fabric8-analytics
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-russian
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-lombok
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension vue.volar
code --install-extension zxh404.vscode-proto3
