code --install-extension 4ops.terraform \
    akamud.vscode-theme-onedark \
    arcticicestudio.nord-visual-studio-code \
    atommaterial.a-file-icon-vscode \
    davidanson.vscode-markdownlint \
    dustypomerleau.rust-syntax \
    eamodio.gitlens \
    github.copilot \
    github.copilot-chat \
    golang.go \
    hashicorp.terraform \
    hediet.vscode-drawio \
    korekontrol.saltstack \
    ms-azuretools.vscode-docker \
    ms-kubernetes-tools.vscode-kubernetes-tools \
    ms-python.debugpy \
    ms-python.isort \
    ms-python.python \
    ms-python.vscode-pylance \ \
    ms-vscode-remote.remote-containers \
    ms-vscode.makefile-tools \
    ms-vscode.vscode-typescript-next \
    rafaelrenanpacheco.darcula-theme \
    redhat.fabric8-analytics \
    redhat.java \
    redhat.vscode-yaml \
    rust-lang.rust-analyzer \
    streetsidesoftware.code-spell-checker \
    streetsidesoftware.code-spell-checker-russian \
    sumneko.lua \
    tamasfe.even-better-toml \
    visualstudioexptteam.intellicode-api-usage-examples \
    visualstudioexptteam.vscodeintellicode \
    vmware.vscode-spring-boot \
    vscjava.vscode-gradle \
    vscjava.vscode-java-debug \
    vscjava.vscode-java-dependency \
    vscjava.vscode-java-pack \
    vscjava.vscode-java-test \
    vscjava.vscode-lombok \
    vscjava.vscode-maven \
    vscjava.vscode-spring-initializr \
    vscode-icons-team.vscode-icons \
    vscodevim.vim \
    vue.volar \
    zxh404.vscode-proto3
